language: c
env:
  matrix:
    - NAME="Sanity checks" DOCKER_IMAGE=sanity-checks COMMAND="c/check.py"
    - NAME="Preprocessing consistency checks" DOCKER_IMAGE=preprocessing-consistency COMMAND="cd c; ./compare.sh -k"
    - NAME="gcc-5" DOCKER_IMAGE=gcc:5 COMMAND="gcc-5 -v --version; cd c; make -j2 CC=gcc-5"
    - NAME="clang-3.9" DOCKER_IMAGE=clang:3.9 COMMAND="clang-3.9 -v --version; cd c; make -j2 CC=clang-3.9"
    - NAME="java" DOCKER_IMAGE=java COMMAND="java/check-compile.sh"

# Hint to TravisCI that we want to use their container infrastructure
sudo: required
services:
  - docker

git:
  # a commit-rate of one commit per minute causes errors, because Travis is too slow
  depth: 3

before_install:
  - docker pull registry.gitlab.com/sosy-lab/software/sv-benchmarks/ci/${DOCKER_IMAGE}

script:
  - docker run --tty --volume "$(pwd):$(pwd)" registry.gitlab.com/sosy-lab/software/sv-benchmarks/ci/${DOCKER_IMAGE} /bin/sh -c "cd $(pwd); ${COMMAND}"
